spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskify
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: taskify
    hibernate:
      ddl-auto: update
    show-sql: true
